export interface Country {
    name: string;
    code: string;
}

export const countries: Country[] = [
    { name: 'Afghanistan', code: 'AFG' },
    { name: 'Albania', code: 'ALB' },
    { name: 'Germany', code: 'DEU' },
    { name: 'Andorra', code: 'AND' },
    { name: 'Angola', code: 'AGO' },
    { name: 'Antigua and Barbuda', code: 'ATG' },
    { name: 'Saudi Arabia', code: 'SAU' },
    { name: 'Algeria', code: 'DZA' },
    { name: 'Argentina', code: 'ARG' },
    { name: 'Armenia', code: 'ARM' },
    { name: 'Australia', code: 'AUS' },
    { name: 'Austria', code: 'AUT' },
    { name: 'Azerbaijan', code: 'AZE' },
    { name: 'Bahamas', code: 'BHS' },
    { name: 'Bangladesh', code: 'BGD' },
    { name: 'Barbados', code: 'BRB' },
    { name: 'Bahrain', code: 'BHR' },
    { name: 'Belgium', code: 'BEL' },
    { name: 'Belize', code: 'BLZ' },
    { name: 'Benin', code: 'BEN' },
    { name: 'Belarus', code: 'BLR' },
    { name: 'Myanmar', code: 'MMR' },
    { name: 'Bolivia', code: 'BOL' },
    { name: 'Bosnia and Herzegovina', code: 'BIH' },
    { name: 'Botswana', code: 'BWA' },
    { name: 'Brazil', code: 'BRA' },
    { name: 'Brunei', code: 'BRN' },
    { name: 'Bulgaria', code: 'BGR' },
    { name: 'Burkina Faso', code: 'BFA' },
    { name: 'Burundi', code: 'BDI' },
    { name: 'Bhutan', code: 'BTN' },
    { name: 'Cabo Verde', code: 'CPV' },
    { name: 'Cambodia', code: 'KHM' },
    { name: 'Cameroon', code: 'CMR' },
    { name: 'Canada', code: 'CAN' },
    { name: 'Qatar', code: 'QAT' },
    { name: 'Chad', code: 'TCD' },
    { name: 'Chile', code: 'CHL' },
    { name: 'China', code: 'CHN' },
    { name: 'Cyprus', code: 'CYP' },
    { name: 'Colombia', code: 'COL' },
    { name: 'Comoros', code: 'COM' },
    { name: 'North Korea', code: 'PRK' },
    { name: 'South Korea', code: 'KOR' },
    { name: 'Ivory Coast', code: 'CIV' },
    { name: 'Costa Rica', code: 'CRI' },
    { name: 'Croatia', code: 'HRV' },
    { name: 'Cuba', code: 'CUB' },
    { name: 'Denmark', code: 'DNK' },
    { name: 'Dominica', code: 'DMA' },
    { name: 'Ecuador', code: 'ECU' },
    { name: 'Egypt', code: 'EGY' },
    { name: 'El Salvador', code: 'SLV' },
    { name: 'United Arab Emirates', code: 'ARE' },
    { name: 'Eritrea', code: 'ERI' },
    { name: 'Slovakia', code: 'SVK' },
    { name: 'Slovenia', code: 'SVN' },
    { name: 'Spain', code: 'ESP' },
    { name: 'United States', code: 'USA' },
    { name: 'Estonia', code: 'EST' },
    { name: 'Eswatini', code: 'SWZ' },
    { name: 'Ethiopia', code: 'ETH' },
    { name: 'Philippines', code: 'PHL' },
    { name: 'Finland', code: 'FIN' },
    { name: 'Fiji', code: 'FJI' },
    { name: 'France', code: 'FRA' },
    { name: 'Gabon', code: 'GAB' },
    { name: 'Gambia', code: 'GMB' },
    { name: 'Georgia', code: 'GEO' },
    { name: 'Ghana', code: 'GHA' },
    { name: 'Grenada', code: 'GRD' },
    { name: 'Greece', code: 'GRC' },
    { name: 'Guatemala', code: 'GTM' },
    { name: 'Guinea', code: 'GIN' },
    { name: 'Equatorial Guinea', code: 'GNQ' },
    { name: 'Guinea-Bissau', code: 'GNB' },
    { name: 'Guyana', code: 'GUY' },
    { name: 'Haiti', code: 'HTI' },
    { name: 'Honduras', code: 'HND' },
    { name: 'Hungary', code: 'HUN' },
    { name: 'India', code: 'IND' },
    { name: 'Indonesia', code: 'IDN' },
    { name: 'Iraq', code: 'IRQ' },
    { name: 'Iran', code: 'IRN' },
    { name: 'Ireland', code: 'IRL' },
    { name: 'Iceland', code: 'ISL' },
    { name: 'Marshall Islands', code: 'MHL' },
    { name: 'Solomon Islands', code: 'SLB' },
    { name: 'Israel', code: 'ISR' },
    { name: 'Italy', code: 'ITA' },
    { name: 'Jamaica', code: 'JAM' },
    { name: 'Japan', code: 'JPN' },
    { name: 'Jordan', code: 'JOR' },
    { name: 'Kazakhstan', code: 'KAZ' },
    { name: 'Kenya', code: 'KEN' },
    { name: 'Kyrgyzstan', code: 'KGZ' },
    { name: 'Kiribati', code: 'KIR' },
    { name: 'Kuwait', code: 'KWT' },
    { name: 'Laos', code: 'LAO' },
    { name: 'Lesotho', code: 'LSO' },
    { name: 'Latvia', code: 'LVA' },
    { name: 'Lebanon', code: 'LBN' },
    { name: 'Liberia', code: 'LBR' },
    { name: 'Libya', code: 'LBY' },
    { name: 'Liechtenstein', code: 'LIE' },
    { name: 'Lithuania', code: 'LTU' },
    { name: 'Luxembourg', code: 'LUX' },
    { name: 'Madagascar', code: 'MDG' },
    { name: 'Malaysia', code: 'MYS' },
    { name: 'Malawi', code: 'MWI' },
    { name: 'Maldives', code: 'MDV' },
    { name: 'Mali', code: 'MLI' },
    { name: 'Malta', code: 'MLT' },
    { name: 'Morocco', code: 'MAR' },
    { name: 'Mauritius', code: 'MUS' },
    { name: 'Mauritania', code: 'MRT' },
    { name: 'Mexico', code: 'MEX' },
    { name: 'Micronesia', code: 'FSM' },
    { name: 'Moldova', code: 'MDA' },
    { name: 'Monaco', code: 'MCO' },
    { name: 'Mongolia', code: 'MNG' },
    { name: 'Montenegro', code: 'MNE' },
    { name: 'Mozambique', code: 'MOZ' },
    { name: 'Namibia', code: 'NAM' },
    { name: 'Nauru', code: 'NRU' },
    { name: 'Nepal', code: 'NPL' },
    { name: 'Nicaragua', code: 'NIC' },
    { name: 'Niger', code: 'NER' },
    { name: 'Nigeria', code: 'NGA' },
    { name: 'Norway', code: 'NOR' },
    { name: 'New Zealand', code: 'NZL' },
    { name: 'Oman', code: 'OMN' },
    { name: 'Netherlands', code: 'NLD' },
    { name: 'Pakistan', code: 'PAK' },
    { name: 'Palau', code: 'PLW' },
    { name: 'Palestine', code: 'PSE' },
    { name: 'Panama', code: 'PAN' },
    { name: 'Papua New Guinea', code: 'PNG' },
    { name: 'Paraguay', code: 'PRY' },
    { name: 'Peru', code: 'PER' },
    { name: 'Poland', code: 'POL' },
    { name: 'Portugal', code: 'PRT' },
    { name: 'United Kingdom', code: 'GBR' },
    { name: 'Central African Republic', code: 'CAF' },
    { name: 'Czech Republic', code: 'CZE' },
    { name: 'Republic of the Congo', code: 'COG' },
    { name: 'Democratic Republic of the Congo', code: 'COD' },
    { name: 'Dominican Republic', code: 'DOM' },
    { name: 'Rwanda', code: 'RWA' },
    { name: 'Romania', code: 'ROU' },
    { name: 'Russia', code: 'RUS' },
    { name: 'Samoa', code: 'WSM' },
    { name: 'Saint Kitts and Nevis', code: 'KNA' },
    { name: 'San Marino', code: 'SMR' },
    { name: 'Saint Vincent and the Grenadines', code: 'VCT' },
    { name: 'Saint Lucia', code: 'LCA' },
    { name: 'Sao Tome and Principe', code: 'STP' },
    { name: 'Senegal', code: 'SEN' },
    { name: 'Serbia', code: 'SRB' },
    { name: 'Seychelles', code: 'SYC' },
    { name: 'Sierra Leone', code: 'SLE' },
    { name: 'Singapore', code: 'SGP' },
    { name: 'Syria', code: 'SYR' },
    { name: 'Somalia', code: 'SOM' },
    { name: 'Sri Lanka', code: 'LKA' },
    { name: 'South Africa', code: 'ZAF' },
    { name: 'Sudan', code: 'SDN' },
    { name: 'South Sudan', code: 'SSD' },
    { name: 'Sweden', code: 'SWE' },
    { name: 'Switzerland', code: 'CHE' },
    { name: 'Suriname', code: 'SUR' },
    { name: 'Thailand', code: 'THA' },
    { name: 'Tanzania', code: 'TZA' },
    { name: 'Tajikistan', code: 'TJK' },
    { name: 'Timor-Leste', code: 'TLS' },
    { name: 'Togo', code: 'TGO' },
    { name: 'Tonga', code: 'TON' },
    { name: 'Trinidad and Tobago', code: 'TTO' },
    { name: 'Tunisia', code: 'TUN' },
    { name: 'Turkmenistan', code: 'TKM' },
    { name: 'Turkey', code: 'TUR' },
    { name: 'Tuvalu', code: 'TUV' },
    { name: 'Ukraine', code: 'UKR' },
    { name: 'Uganda', code: 'UGA' },
    { name: 'Uruguay', code: 'URY' },
    { name: 'Uzbekistan', code: 'UZB' },
    { name: 'Vanuatu', code: 'VUT' },
    { name: 'Vatican City', code: 'VAT' },
    { name: 'Venezuela', code: 'VEN' },
    { name: 'Vietnam', code: 'VNM' },
    { name: 'Yemen', code: 'YEM' },
    { name: 'Djibouti', code: 'DJI' },
    { name: 'Zambia', code: 'ZMB' },
    { name: 'Zimbabwe', code: 'ZWE' }
];
